use_frameworks!

platform :ios, '9.3'

target 'TTouchAnimatedButton_Example' do
  pod 'TTouchAnimatedButton', :path => '../'

  target 'TTouchAnimatedButton_Tests' do
    inherit! :search_paths

    
  end
end
